### PR TITLE
Project: Newsweek.com's clone website using bootstrap

### PR DESCRIPTION
**Pull request by hemantso**
## Project: Newsweek.com's clone website using bootstrap
- Header with logo, navigation links, and authentication links
- Use of grid and flex with bootstrap for different sections
- Use of semantic tags
- Sections like Featured Stories, Top Stories, Opinion, editor's pick, etc
- Footer with navigation links

### CODE REVIEW

**Comment by Dandush03** [comment]
# :red_circle: Status Require: changes :face_with_monocle:
### Hey @hemant-soni-vst-au4  :wave: 
Good attempts on this one :muscle: :+1: 
But there are some very important things you have to consider before stepping ahead in the issues below :point_down: 
### :one: This is a project to learn how to implement Bootstrap therefore most of your classes should be called through Bootstrap.
### :two: At this point you probably already mastered Git. You should have more commits during your project, otherwise, we will be forced to mark this project as invalid 

## Here are the issues to address to get the project meet the requirement:wink:

#### Phone Resolution (Width: 375px)

---

## Header
- [x] The Nav-Bar element aren't aligned
- [x] The Nav-Bar is missing the toggle button
- [x] Subscribe Button missing padding
##### Required:
Screenshot from 2020-03-24 20-20-40
##### Yours: 
Screenshot from 2020-03-24 20-20-21

---

## More Stories Section 
- [x] Content should be overflowing below the image
- [x] Image should be smaller
##### Required:
Screenshot from 2020-03-24 20-21-32
##### Yours: 
Screenshot from 2020-03-24 20-21-20

---

## Lastest News Section
- [x] Image is too big
##### Required:
Screenshot from 2020-03-24 20-22-18
##### Yours: 
Screenshot from 2020-03-24 20-22-11

---

## In the Magazine Section
- [x] Image should be insed this section
##### Required:
Screenshot from 2020-03-24 20-23-07
##### Yours: 
Screenshot from 2020-03-24 20-22-58

---

## Footer Section
- [x] Logo should remain on the left side but inside the boundaries of all the other elements ( Logo is not aligned with the current context)
- [x]  The footer doesn't display media-icons
- [x]  The footer element isn't aligned as the original page
##### Required:
Screenshot from 2020-03-24 20-24-23
##### Yours: 
Screenshot from 2020-03-24 20-24-15

---

#### Pad Resolution (Width: 768px):

---

## HeaderBar
- [ ] The Header-Bar & Nav-Bar aren't aligned and content it's not readable (Remember this page should look alike the original)
##### Required:
Screenshot from 2020-03-24 19-58-10
##### Yours: 
Screenshot from 2020-03-24 19-58-25

---

## More Stories Section:
- [x] The content should overflow below the image in this resolution 
##### Required:
Screenshot from 2020-03-24 19-59-55
##### Yours:
Screenshot from 2020-03-24 20-00-05

---

## The Magazine Section:
- [x] All images should be adjusted to create a square like a view
- [x] add image (on the top left) should keep the original size related to the current resolution (see examples)
##### Required:
Screenshot from 2020-03-24 20-01-27
##### Yours:
Screenshot from 2020-03-24 20-01-35

--- 

## The Subscribe & Newsletter Section:
- [x] Image should remain on the left side, text in the right size
- [x] Recreate the proper alignment for the elements
##### Required:
Screenshot from 2020-03-24 20-02-56
##### Yours:
Screenshot from 2020-03-24 20-02-32

---

## The Footer
- [x] Logo should remain on the left side but inside the boundaries of all the other elements ( Logo is not aligned with the current context)
- [x]  The footer doesn't display media-icons
- [x]  The footer element isn't aligned as the original page
##### Required:
Screenshot from 2020-03-24 20-14-07
##### Yours: 
Screenshot from 2020-03-24 20-02-46

---

#### Maximum Resolution:

---

## HeaderBar
- [x]  The Items in the header-bar aren't aligned properly.
- [x] The subscribe button need to have more padding so it will actually look alike 
##### Required:
Screenshot from 2020-03-24 19-28-47
##### Yours: 
Screenshot from 2020-03-24 19-27-56

---

## NavBar
- [x]  The navbar search section should be aligned to the left
- [x]  The font in the navbar should be bolder
- [x]  The rightmost part of the navbar should be like the original page
##### Required:
Screenshot from 2020-03-24 19-29-05
##### Yours: 
Screenshot from 2020-03-24 19-29-13

---

## Content
- [x]  Feature Stories section should be wider to meet the original page standarts 
- [x]  Make sure all the titles are well aligned to the middle as displayed in the original page
##### Required:
Screenshot from 2020-03-24 19-33-34
##### Yours: 
Screenshot from 2020-03-24 19-33-24

--

## Footer
- [x]  The footer doesn't display media-icons
- [x]  The footer Newsweek logo isn't align with the content
- [x]  The footer element aren't aligned as the original page
##### Required:
Screenshot from 2020-03-24 19-34-31
##### Yours: 
Screenshot from 2020-03-24 19-48-29

---

## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by hemantso** [comment]
## All corrections are completed as recommended by TSE

**Comment by uryelah** [comment]
Hello **Hemant Soni**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, good job with the fixes from the last review 🌟**

Your project is almost good to go, you are just missing one requirement. You got this! 💪

---------    

## Required Changes

- [x] Make sure that all of the Stickler linter checks pass.

- [x] The side column images from the topics, articles should have all of its article image aligned and with the same height and width. Check how your images look right now in wide and small screens:
Screenshot_2020-03-25 Newsweek(23)
Screenshot_2020-03-25 Newsweek(22)

 ----

- [x] The topics side column articles should be aligned with the ones in the left and take no extra height.
**Your version:**
Screenshot_2020-03-25 Newsweek(24)
**Original version:**
Screenshot_2020-03-25 Newsweek(25)

-----

- [ ] The sections above 'In the Magazine' are all aligned in the bottom regardless of their heights. Try to implement that using overflow scroll or similar. There should be no empty spaces like you currently have in the screencap below:
Screenshot_2020-03-25 Newsweek(26)

----

- [ ] Make sure the icons in the footer have the correct size.
Screenshot_2020-03-25 Newsweek(27)
**Original footer:**
Screenshot_2020-03-25 Newsweek(28)


---------

Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding!👏👏👏

Code review by Sarah Uryelah Silva Chamorro

(Feel free to contact me on slack by the handle of sarah if you have any additional question)

**Comment by mikenath223** [comment]
**Pull request currently under review by Michgolden Ukeje (TSE).**
Kindly exercise patience 🐱

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS @hemant-soni-vst-au4 🎉🎉🎉

You've met the minimum requirements for approval 👏

**STATUS: APPROVED✅**

However consider making these changes, I trust you would do them before merging:👇

- [x] Add a menu icon to the top navbar of your page.[Screenshot]

**THIS IS YOURS👇**
ice_screenshot_20200326-093215

**YET THIS IS THE WAY IT LOOKS ON THE ORIGINAL WEBPAGE👇**
ice_screenshot_20200326-095030

I trust you will make this change before merging. Kindly do that.

Once more, your code looks neat and concise👌
**Great JOB 👍**

Don't forget to submit your project completion form.
Good luck with the next project.

**HAPPY CODING👨‍💻**

**Comment by hemantso** [comment]
## Navbar icons fixed now
- Thank you TSE for your valuable reviews

**Pull request merged**
